language: node_js
node_js:
- '7'
deploy:
  provider: npm
  email: jingkai.zhao@foxmail.com
  api_key:
    secure: rT0/T2eUMyxdD2KbUt3kDfUs9Q7aqtuhPD+T5oyOJUtaPkPXLUv0ykKPfKw9k6jGpPuvc/Go00rpewaovbrVNCbaq8IrWUQnyB0dGMfz3dOCVYoQCyJH9Z9re9FmQ6PPtwxtk/8SvLKdLhnsEXjBdLmP7UXx5lCGtJkSn0XAG75QHQu0Nd7FPo0eTnHhJKqVSw7tzWpLLZqPnN6ByIUmgeNsPnSb3sp2bxFS8KaggT6RI9EEp3fPUMKcIVDrumX2Aqf9mfgJ8A5IcTKx0J9vC/a9pc9uSMyNZp8JuHsgftarze7CA/LkleL8HmtUX/QSKAnMpvy1T3bzSKRj8nIcelXJLcudJyxpQj8NGg0n21exJTPYxK+iNEcEo9seOvxUVLuX51pe4Bov/vxsS98X47/dkRjGBYFhOFLEsPwgr9XxvDklgqsOPKy1x6o7A2eq5A6/NYHzGXWRC9+cWzGfmuM7XpLUfEFjrN1U+Fv2sfkDv981+r3Z6lPDjrmQigjqDf6chtuxoDlMTMRuGX2j8AF/BKBK9iq8yYW8UfY2/Mia2F0hRh6YEHF7H78GpRLlZ7jSi2LgXVPIFif4zPYwtxnxzUUMtazW0RMWvSgZz8zi7VQQkPxYV4rvZIxbpHUZ0oydDBZaPUbhpY7ye91JYi8/jnOoWoysmCHedWxJkYU=
  on:
    repo: hui-z/h-qrcode
    tags: true
    branch: master
