language: node_js
node_js:
- '7'
deploy:
  provider: npm
  email: jingkai.zhao@foxmail.com
  api_key:
    secure: axTsRnIt5IQcMb6Cgv2FmEMgU/5TlL/XjgsYk1O9cwRH+w0FBX+7nkGqi8u7tdEt9mQ2PUyj79gBuBeuLgDssWkuue11xSoYezprMg1Qgp3mld+AL0hR3oMoD9T1GNsELlLT+adPx8Q0KUInb8gG61/bKvvI2uReR4nmP3G3dWEtDgNjN8gCz5fnmzLi61YJVo0XT1ZeOKACTlbiB8bTjxBDcuyDHebx/0PKCXu1MaMOR9eK4Eom4IPVhmCQbLkCc2GYE6xi2KxBXfBk98a7HweuA6jxPAe4YO/GGpJUXBv04cNYjg/lFJiCiSfEdwcdlncU1hOwL8/I2sFZjoVNMwLFPVktw1Jfw8k4QyI3W5VkGagL33Y3H7NKN9iIZ9VXOWExMNnr8Wew8DxLK3sntFLeVtxPcG8KEfdAk+nVbUHN5AlWGpamJFJoW3VeDh43EPuiArD3nPP0NsrbsOq2c0WPFyhJPHfA+EQwBPEsfEbpDMg5q3WURu6i0ULoxA9Ud+0W/jXDjbsszT7sN3CBnbezlLA0raOMNjxJVRxnmd/+wpkSDXA0pInQOEMDxNkNRIMle6edCOzkbW4vZ6L33w/GRQJvYuF1PVK6Nh7lwIcB+FxHrPVMghhugKtdBi16qnYit8lJz4xhjgSmKG2fXf/jBkkggNGz/gnLbKUB+jY=
  on:
    tags: true
    repo: hui-z/h-qrcode
    branch: master
